name: encrypt_env
description: |
  Generate encrypted files to secure sensitive configuration data. 
  Encrypt YAML files and streamline the protection of sensitive information in Flutter applications.
version: 2.0.2
maintainer: Eduardo Natale Costa (@edunatalec)
homepage: https://github.com/edunatalec/encrypt-env

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  yaml: ^3.1.3
  pub_updater: ^0.5.0

dev_dependencies:
  test: ^1.26.3
  build_runner: ^2.7.1
  build_version: ^2.1.2
  lints: ^5.1.1

executables:
  encrypt_env:

topics:
  - encryption
  - environment
  - security
  - dotenv
  - cryptography
